version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    restart: always
  app-with-cache:
    container_name: app-with-cache
    build:
      context: .
      dockerfile: dockerfile
    image: danielsuhett/app-redis
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3001:3000
    depends_on:
      - redis
    env_file:
      - .env
